stages:
  salience:
    cmd: >
        papermill 
        nbs/salience.ipynb 
        scripts/salience.ipynb
        -p IMAGE_PATH ${salience.image_path}
        -p MODEL_PATH ${salience.model_path}
        -p NETWORK ${salience.network}
        -p GRADCAM_TYPE ${salience.gradcam_type}
        -p SIZE ${salience.size}
        -p OUTPUT_PATH ${salience.output_path}
    deps:
    - pdm.lock
    - pyproject.toml
    - nbs/salience.ipynb
    - ${salience.image_path}
    - ${salience.model_path}
    outs:
    - scripts/salience.ipynb
    plots:
    - ${salience.output_path}