stages:
  noise:
    cmd: jupyter nbconvert --to python --execute nbs/noise.ipynb --output ../scripts/noise.py
    deps:
    - pdm.lock
    - pyproject.toml
    - nbs/noise.ipynb
    - data/images/ffhq_aligned/000001.png
  evaluate:
    cmd: ./install-quarto.sh
    deps:
    - data/images
    - nbs/noise.ipynb
  salience:
    cmd: jupyter nbconvert --to python --execute nbs/salience.ipynb --output ../scripts/salience.py
    deps:
    - pdm.lock
    - pyproject.toml
    - nbs/salience.ipynb
    - data/images/ffhq_aligned/00001.png
    outs:
    - scripts/salience.py
    plots:
    - output/cams/00001.png