stages:
  noise:
    cmd: >
        papermill 
        nbs/noise.ipynb 
        scripts/noise.ipynb
        -p DATASET ${noise.dataset}
        -p MODEL_PATH ${noise.model_path}
        -p NETWORK ${noise.network}
        -p ANOUNT ${noise.amount}
        --cwd nbs/
    deps:
    - pdm.lock
    - pyproject.toml
    - nbs/noise.ipynb
    outs:
    - scripts/noise.ipynb
    - eval/plots/images:
        persist: false