[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "dvc>=2.45.1",
    "nbdev>=2.3.12",
]
requires-python = ">=3.9"
license = {text = "MIT"}
