# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Explain2Me-Framework-Example',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/Explain2Me-Framework-Example',
                'lib_path': 'Explain2Me_Framework_Example'},
  'syms': {}}
